#! /usr/bin/zsh
### List the paths of all files/directories in DIR edited AGE or fewer days ago (and modification times, for files).  
# Prints the straight find output for directories; for files gets the modification time from ls -l (for directories that time doesn't seem to be anything sensible)
# Ignores .* files and anything in .git directories.  Follows symbolic links.
# -- Weronika Patena, oct 2011

# USAGE:
# check_new_files [DIR] [AGE] [TYPE]
#   DIR is the directory to check - default current directory; a value of e expands to ~/experiments
#   AGE is how many days to look back - default 7
#   TYPE can be f for file or d for directory - default f, switch to d if you want a shorter list
#       arguments can be given in any order - they're distinguished by type/value

DIR=`pwd`
AGE=7
TYPE=f

if [[ $#* > 3 ]]; then
    echo "Error: can't pass more than three arguments! See file comment header for usage/info."
    exit
fi

# arguments can be given in any order - they're distinguished by value:
for i in $*; do
    # a value of f or d is TYPE
    if [[ $i = f || $i = d ]]; then
        TYPE=$i
    # a value that's a number is AGE
    elif [[ $i = <-> ]]; then     # <-> matches any number of digits
        AGE=$i
    # any other value is DIR (and e means ~/experiments)
    else
        if [[ $i = e ]]; then
            DIR=~/experiments
        else
            DIR=$i
        fi
    fi
done

echo '\t'DIR is $DIR
echo '\t'AGE is $AGE
echo '\t'TYPE is $TYPE

### core functionality
# for directories, just print the find output straight - I 
if [[ $TYPE = d ]]; then
    find -L $DIR -mtime -$AGE -type $TYPE -not -iname ".*" -not -path "*.git*"
# for files, get modification times from ls -l output, it's nicer-looking
else
    for i in `find -L $DIR -mtime -$AGE -type $TYPE -not -iname ".*" -not -path "*.git*"`;  do
        line=`ls -ld $i`
        line=`echo $line | sed 's/\/home\/weronika/  ~/'`
        line=`echo $line | cut -d ' ' -f 6-`
        echo $line
    done
fi
# MAYBE:TODO try something like the above version for directories?  But the modification times reported by ls -ld can be very different from the modification time of containing files!

# TODO replace '/home/weronika' in the output with '~' to make the lines shorter!  Or possibly just replace the entire DIR path prefix with '$DIR' or an empty string or something.
